# Generated by Django 6.0.3 on 2026-05-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('send_at', models.DateTimeField(auto_now_add=True)),
                ('message_type', models.CharField(choices=[('OTP', 'Otp'), ('NOTIFICATION', 'Notification')], max_length=50)),
            ],
        ),
    ]
