# Generated by Django 6.0.3 on 2026-09-09 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0029_permitapplication_aic_issued_at_and_more'),
        ('sms', '0002_smslog_status_captured'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='permits.permitapplication'),
        ),
    ]
