# Generated by Django 6.0.3 on 2026-04-07 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('permits', '0003_alter_opvvalidation_application_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='permit',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='issued_permit',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='permit', to='permits.issuedpermit'),
            preserve_default=False,
        ),
    ]
