# Generated by Django 6.0.3 on 2026-04-10 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_paymenthistory_permit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='reference_number',
        ),
    ]
