# Generated by Django 6.0.3 on 2026-04-10 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_paymenthistory_reference_number'),
        ('permits', '0005_alter_permitapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='issued_permit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permit', to='permits.issuedpermit'),
        ),
    ]
