# Generated by Django 6.0.3 on 2026-04-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_paymenthistory_issued_permit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('SUCCESS', 'success'), ('FAILED', 'Failed')], default='PENDING', max_length=10),
        ),
    ]
