# Generated by Django 6.0.3 on 2026-04-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_paymenthistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='method',
            field=models.CharField(choices=[('paymaya', 'Paymaya'), ('gcash', 'Gcash'), ('card', 'Card')], max_length=10),
        ),
    ]
