# Generated by Django 6.0.3 on 2026-04-10 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_paymenthistory_method'),
        ('permits', '0010_alter_issuedpermit_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='issued_permit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='permits.issuedpermit'),
        ),
    ]
