# Generated by Django 6.0.3 on 2026-07-23 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_paymenthistory_issued_permit'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='or_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
