# Generated by Django 6.0.3 on 2026-08-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_paymenthistory_or_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='paymongo_payment_intent_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='method',
            field=models.CharField(choices=[('paymaya', 'Paymaya'), ('gcash', 'Gcash'), ('card', 'Card'), ('qrph', 'Sari-Sari Store (QR Ph)')], max_length=10),
        ),
    ]
