# Generated by Django 6.0.3 on 2026-09-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_paymenthistory_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='method',
            field=models.CharField(choices=[('paymaya', 'Paymaya'), ('gcash', 'Gcash'), ('card', 'Card'), ('qrph', 'Sari-Sari Store (QR Ph)'), ('ONLINE', 'Online')], max_length=10),
        ),
    ]
