# Generated by Django 6.0.3 on 2026-08-21 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30)),
                ('scope_key', models.CharField(db_index=True, help_text='Unique scope key e.g. user_12, barangay_1, municipal_agri', max_length=120)),
                ('summary', models.TextField(help_text='Plain English executive summary of what is happening.')),
                ('trends', models.JSONField(default=list, help_text="List of trend objects with {text: str, severity: 'positive'|'warning'|'critical'|'neutral'}")),
                ('actions', models.JSONField(default=list, help_text='List of recommended actionable next steps.')),
                ('raw_metrics_snapshot', models.JSONField(blank=True, default=dict, help_text='Snapshot of the period-over-period numbers used to generate this insight.')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cached_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['role', 'scope_key'], name='dashboard_c_role_34c8bc_idx')],
            },
        ),
    ]
