# Generated by Django 6.0.3 on 2026-04-15 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0001_initial'),
        ('permits', '0014_alter_opvvalidation_application'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectorlogs',
            name='application',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='inspector_application', to='permits.permitapplication'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inspectorlogs',
            name='inspector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspector', to=settings.AUTH_USER_MODEL),
        ),
    ]
