# Generated by Django 6.0.3 on 2026-04-15 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0002_inspectorlogs_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectorlogs',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='inspectorlogs',
            name='longi',
            field=models.FloatField(default=0),
        ),
    ]
