# Generated by Django 6.0.3 on 2026-09-30 15:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyOCRUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('provider', models.CharField(db_index=True, max_length=30)),
                ('call_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Daily OCR Usage',
                'verbose_name_plural': 'Daily OCR Usage',
                'unique_together': {('date', 'provider')},
            },
        ),
    ]
