# Generated by Django 6.0.3 on 2026-04-06 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HogSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_date', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('inahin', models.PositiveIntegerField(default=0)),
                ('barako', models.PositiveIntegerField(default=0)),
                ('fattener', models.PositiveIntegerField(default=0)),
                ('grower', models.PositiveIntegerField(default=0)),
                ('bulaw', models.PositiveIntegerField(default=0)),
                ('starter', models.PositiveIntegerField(default=0)),
                ('total_pigs', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.barangay')),
            ],
            options={
                'ordering': ['-survey_date'],
            },
        ),
    ]
