# Generated by Django 6.0.3 on 2026-04-06 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_hogsurvey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barangay',
            options={'ordering': ['name']},
        ),
    ]
