# Generated by Django 6.0.3 on 2026-04-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_alter_barangay_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hogsurvey',
            name='survey_date',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
    ]
