# Generated by Django 6.0.3 on 2026-09-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_alter_hogsurvey_survey_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hogsurvey',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='hogsurvey',
            name='farmer_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
