# Generated by Django 6.0.3 on 2026-04-06 11:15

import apps.permits.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermitApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(default=apps.permits.models.document_id, editable=False, max_length=12, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('OCR_VALIDATED', 'OCR Validated'), ('MANUAL', 'Manual Review'), ('FORWARDED_TO_OPV', 'Forwarded to OPV'), ('OPV_VALIDATED', 'OPV Validated'), ('OPV_REJECTED', 'OPV Rejected'), ('PERMIT_ISSUED', 'Permrit issued'), ('PAYMENT_PENDING', 'Payment pending'), ('RELEASED', 'Released')], default='DRAFT', max_length=50)),
                ('destination', models.CharField(max_length=255)),
                ('number_of_pigs', models.PositiveIntegerField()),
                ('transport_date', models.DateField()),
                ('purpose', models.TextField(blank=True)),
                ('is_issued', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('origin_barangay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin', to='maps.barangay')),
            ],
            options={
                'ordering': ['-created_at', 'status'],
            },
        ),
        migrations.CreateModel(
            name='OPVValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VALIDATED', 'Validated'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('validated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('veterinary_health_certificate', models.FileField(blank=True, null=True, upload_to='opv_docs/vhc/')),
                ('transportation_pass', models.FileField(blank=True, null=True, upload_to='opv_docs/pass/')),
                ('opv_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='permits.permitapplication')),
            ],
        ),
        migrations.CreateModel(
            name='IssuedPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_number', models.CharField(editable=False, max_length=13, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, default='', max_length=100)),
                ('permit_pdf', models.FileField(blank=True, null=True, upload_to='issued_docs/vhc/')),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('valid_until', models.DateField(null=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='permits.permitapplication')),
            ],
        ),
        migrations.CreateModel(
            name='SubmittedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('traders_pass', "Trader's Pass"), ('handlers_license', "Handler's License"), ('transport_carrier_reg', 'Transport Carrier Registration'), ('cis', 'CIS (Barangay-issued)'), ('endorsement_cert', 'Endorsement Certificate')], max_length=30)),
                ('file', models.FileField(upload_to='submitted_docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='permits.permitapplication')),
            ],
        ),
        migrations.CreateModel(
            name='OCRValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PASSED', 'Passed'), ('MANUAL', 'Needs Manual Review')], max_length=20)),
                ('extracted_field', models.JSONField(default=dict)),
                ('remarks', models.JSONField(default=dict)),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
                ('manually_overridden', models.BooleanField(default=False)),
                ('overridden_at', models.DateTimeField(blank=True, null=True)),
                ('overridden_fields', models.JSONField(default=dict)),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr', to='permits.submitteddocument')),
            ],
        ),
    ]
