# Generated by Django 6.0.3 on 2026-04-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedpermit',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], default='', max_length=100),
        ),
    ]
