# Generated by Django 6.0.3 on 2026-04-07 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0002_alter_issuedpermit_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opvvalidation',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permit_application', to='permits.permitapplication'),
        ),
        migrations.AlterUniqueTogether(
            name='submitteddocument',
            unique_together={('application', 'document_type')},
        ),
    ]
