# Generated by Django 6.0.3 on 2026-04-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0003_alter_opvvalidation_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedpermit',
            name='qr_token',
            field=models.CharField(default='', editable=False, max_length=36),
            preserve_default=False,
        ),
    ]
