# Generated by Django 6.0.3 on 2026-04-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0004_issuedpermit_qr_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permitapplication',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('RESUBMISSION', 'Resubmission'), ('OCR_VALIDATED', 'OCR Validated'), ('MANUAL', 'Manual Review'), ('FORWARDED_TO_OPV', 'Forwarded to OPV'), ('OPV_VALIDATED', 'OPV Validated'), ('OPV_REJECTED', 'OPV Rejected'), ('PERMIT_ISSUED', 'Permrit issued'), ('PAYMENT_PENDING', 'Payment pending'), ('RELEASED', 'Released')], default='DRAFT', max_length=50),
        ),
    ]
