# Generated by Django 6.0.3 on 2026-04-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0005_alter_permitapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedpermit',
            name='qr_token',
            field=models.CharField(editable=False, max_length=36, unique=True),
        ),
    ]
