# Generated by Django 6.0.3 on 2026-04-10 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0006_alter_issuedpermit_qr_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuedpermit',
            name='qr_code',
        ),
    ]
