# Generated by Django 6.0.3 on 2026-04-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0007_remove_issuedpermit_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedpermit',
            name='permit_pdf',
            field=models.FileField(blank=True, null=True, upload_to='issued_docs/permits/'),
        ),
    ]
