# Generated by Django 6.0.3 on 2026-04-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0008_alter_issuedpermit_permit_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitapplication',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
