# Generated by Django 6.0.3 on 2026-04-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0010_alter_issuedpermit_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrvalidationresult',
            name='is_overridden',
            field=models.BooleanField(default=False),
        ),
    ]
