# Generated by Django 6.0.3 on 2026-04-13 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0011_ocrvalidationresult_is_overridden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocrvalidationresult',
            name='is_overridden',
        ),
    ]
