# Generated by Django 6.0.3 on 2026-04-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0012_remove_ocrvalidationresult_is_overridden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrvalidationresult',
            name='status',
            field=models.CharField(choices=[('PASSED', 'Passed'), ('MANUAL', 'Needs Manual Review'), ('OVERRIDDEN', 'Overridden')], max_length=20),
        ),
    ]
