# Generated by Django 6.0.3 on 2026-04-14 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0013_alter_ocrvalidationresult_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opvvalidation',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='opv_validation', to='permits.permitapplication'),
        ),
    ]
