# Generated by Django 6.0.3 on 2026-04-17 13:07

import apps.permits.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0014_alter_opvvalidation_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedpermit',
            name='permit_pdf',
            field=models.FileField(blank=True, null=True, upload_to='issued_docs/permits/', validators=[apps.permits.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='opvvalidation',
            name='transportation_pass',
            field=models.FileField(blank=True, null=True, upload_to='opv_docs/pass/', validators=[apps.permits.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='opvvalidation',
            name='veterinary_health_certificate',
            field=models.FileField(blank=True, null=True, upload_to='opv_docs/vhc/', validators=[apps.permits.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='submitteddocument',
            name='file',
            field=models.FileField(upload_to='submitted_docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), apps.permits.models.validate_file_size]),
        ),
    ]
