# Generated by Django 6.0.3 on 2026-05-07 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_alter_hogsurvey_survey_date'),
        ('permits', '0016_alter_permitapplication_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permitapplication',
            name='number_of_pigs',
        ),
        migrations.RemoveField(
            model_name='permitapplication',
            name='origin_barangay',
        ),
        migrations.CreateModel(
            name='TransportOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_pigs', models.PositiveIntegerField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origins', to='permits.permitapplication')),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.barangay')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='submitteddocument',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='submitteddocument',
            name='origin',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='permits.transportorigin'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='submitteddocument',
            unique_together={('origin', 'document_type')},
        ),
        migrations.RemoveField(
            model_name='submitteddocument',
            name='application',
        ),
    ]
