# Generated by Django 6.0.3 on 2026-05-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0017_remove_permitapplication_number_of_pigs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permitapplication',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('RESUBMISSION', 'Resubmission'), ('OCR_VALIDATED', 'OCR Validated'), ('MANUAL', 'Waiting for Manual Review'), ('FORWARDED_TO_OPV', 'Forwarded to OPV'), ('OPV_VALIDATED', 'OPV Validated'), ('OPV_REJECTED', 'OPV Rejected'), ('PERMIT_ISSUED', 'Permit issued'), ('PAYMENT_PENDING', 'Payment pending'), ('RELEASED', 'Released')], default='DRAFT', max_length=50),
        ),
    ]
