# Generated by Django 6.0.3 on 2026-06-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0018_alter_permitapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitapplication',
            name='is_scanned',
            field=models.BooleanField(default=False),
        ),
    ]
