# Generated by Django 6.0.3 on 2026-06-03 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0019_permitapplication_is_scanned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permitapplication',
            old_name='is_scanned',
            new_name='is_checked',
        ),
    ]
