# Generated by Django 6.0.3 on 2026-06-11 02:19

import apps.permits.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0020_rename_is_scanned_permitapplication_is_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permitapplication',
            name='application_id',
            field=models.CharField(default=apps.permits.models.document_id, editable=False, max_length=18, unique=True),
        ),
    ]
