# Generated by Django 6.0.3 on 2026-07-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0022_alter_permitapplication_application_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportorigin',
            name='barako',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transportorigin',
            name='bulaw',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transportorigin',
            name='fattener',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transportorigin',
            name='grower',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transportorigin',
            name='inahin',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transportorigin',
            name='starter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transportorigin',
            name='number_of_pigs',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
