# Generated by Django 6.0.3 on 2026-07-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0023_transportorigin_barako_transportorigin_bulaw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedpermit',
            name='permit_fee',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=10),
        ),
    ]
