# Generated by Django 6.0.3 on 2026-07-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0024_issuedpermit_permit_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='MunicipalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_fee', models.DecimalField(decimal_places=2, default=150.0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
