# Generated by Django 6.0.3 on 2026-07-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0025_municipalconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipalconfig',
            name='permit_fee',
        ),
        migrations.AddField(
            model_name='municipalconfig',
            name='local_transport_permit_fee',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='municipalconfig',
            name='transport_pass_fee',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='municipalconfig',
            name='validity_days',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='municipalconfig',
            name='vet_health_cert_fee',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
    ]
