# Generated by Django 6.0.3 on 2026-07-23 01:28

import apps.permits.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0026_remove_municipalconfig_permit_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedpermit',
            name='aic_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='issuedpermit',
            name='aic_pdf',
            field=models.FileField(blank=True, null=True, upload_to='issued_docs/aic/', validators=[apps.permits.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='municipalconfig',
            name='oic_name',
            field=models.CharField(default='AMALITA C. AMORES', max_length=100),
        ),
        migrations.AddField(
            model_name='municipalconfig',
            name='oic_title',
            field=models.CharField(default='OIC - Municipal Agriculturist', max_length=100),
        ),
    ]
