# Generated by Django 6.0.3 on 2026-09-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0027_issuedpermit_aic_number_issuedpermit_aic_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportorigin',
            name='source_farmer_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='transportorigin',
            name='source_phone_no',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
