# Generated by Django 6.0.3 on 2026-09-09 00:56

import apps.permits.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0028_transportorigin_source_farmer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitapplication',
            name='aic_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permitapplication',
            name='aic_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='permitapplication',
            name='aic_pdf',
            field=models.FileField(blank=True, null=True, upload_to='issued_docs/aic/', validators=[apps.permits.models.validate_file_size]),
        ),
    ]
