# Generated by Django 6.0.3 on 2026-09-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0029_permitapplication_aic_issued_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AicNumberCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(editable=False, unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
