# Generated by Django 6.0.3 on 2026-09-12 14:59

import apps.permits.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0030_aicnumbercounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermitApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('traders_pass', "Trader's Pass"), ('handlers_license', "Handler's License"), ('transport_carrier_reg', 'Transport Carrier Registration')], max_length=30)),
                ('file', models.FileField(upload_to='submitted_docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), apps.permits.models.validate_file_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_documents', to='permits.permitapplication')),
            ],
            options={
                'unique_together': {('application', 'document_type')},
            },
        ),
    ]
