# Generated by Django 6.0.3 on 2026-09-15 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0031_add_permit_application_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='opvvalidation',
            name='aic_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opvvalidation',
            name='aic_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
