# Generated by Django 6.0.3 on 2026-10-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0033_add_provider_field_to_ocr_validation_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedpermit',
            name='payment_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permitapplication',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('RESUBMISSION', 'Resubmission'), ('OCR_VALIDATED', 'OCR Validated'), ('MANUAL', 'Waiting for Manual Review'), ('FORWARDED_TO_OPV', 'Forwarded to OPV'), ('OPV_VALIDATED', 'OPV Validated'), ('OPV_REJECTED', 'OPV Rejected'), ('PERMIT_ISSUED', 'Permit issued'), ('PAYMENT_PENDING', 'Payment pending'), ('RELEASED', 'Released'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=50),
        ),
    ]
