# Generated by Django 6.0.3 on 2026-04-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('WARNING', 'Warning'), ('INFO', 'Info'), ('SUCCESS', 'Success')], max_length=20),
        ),
    ]
