# Generated by Django 6.0.3 on 2026-04-17 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_audittrail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittrail',
            name='who_performed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
