# Generated by Django 6.0.3 on 2026-05-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_audittrail_who_performed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receive_sms',
            field=models.BooleanField(default=True, help_text='Whether the user wants to receive SMS notifications.'),
        ),
    ]
