# Generated by Django 6.0.3 on 2026-05-28 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_receive_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid mobile number.', regex='^(?:\\+639|639|09)\\d{9}$')]),
        ),
    ]
