# Generated by Django 6.0.3 on 2026-06-22 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_user_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid mobile number.', regex='^(?:\\+639|639|09)\\d{9}$')]),
        ),
    ]
