# Generated by Django 6.0.3 on 2026-08-15 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_user_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Farmer', 'Farmer'), ('Inspector', 'Inspector'), ('Opv', 'Opv'), ('Agri', 'Agri'), ('Barangay', 'Barangay Official')], default='Farmer', help_text='User role', max_length=20),
        ),
    ]
