# Generated by Django 6.0.3 on 2026-09-04 01:13

import apps.api.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING_REVIEW', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='UNVERIFIED', help_text='Farmer KYC document verification status', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_farmers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FarmerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('handlers_license', "Handler's License"), ('transport_carrier_reg', 'Transport Carrier Registration'), ('traders_pass', "Trader's Pass")], max_length=30)),
                ('file', models.FileField(upload_to='farmer_licenses/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), apps.api.models.validate_license_file_size])),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'document_type')},
            },
        ),
    ]
