# Generated by Django 6.0.3 on 2026-09-04 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_verification_remarks_user_verification_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerdocument',
            name='extracted_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='farmerdocument',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmerdocument',
            name='ocr_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
